### ISSUE TITLE
Symbolic link walking

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/in-toto-golang#32]
**Description of issue or feature request**: in-toto golang and the python/java implementations should have consistent behaviors when running into symbolic links

**Current behavior**: The current behavior when runlib runs into a symlink is currently not defined.

**Expected behavior**: [In-toto should dereference the symlinks and track them in the same way the python implementation does](https://github.com/in-toto/in-toto/blob/develop/in_toto/runlib.py#L162)

**Comment by darshildpatel** [comment]
I am taking a look at the issue now.

**Comment by darshildpatel** [comment]
While resolving this issue, I was able to resolve the symlinks that are present in the same directories. What this means is the code is able to resolve the symlinks which have absolute paths in there creation or have a relative path starting from the same directory. Currently am facing problems with resolving the symlinks which have relative paths in symlinks creation.  Please suggest as to what approach should be taken.

**Comment by SantiagoTorres** [comment]
Hmm, care to share a MWE of the issue? I think it'd be easier to look at it.

Does this behavior happen with the python reference implementation too?

**Comment by lukpueh** [comment]
I agree with @SantiagoTorres, we need more details about the problems you're facing in order to help you. Also, have you looked at [`fastwalk`](https://godoc.org/golang.org/x/tools/internal/fastwalk) from [Go tools](https://github.com/golang/tools)? It seems to support symlinks, with the following caveat: 
> It is the walkFn's responsibility to prevent fastWalk from going into symlink cycles.

**Comment by darshildpatel** [comment]
@SantiagoTorres I have committed the clean recursive solution to my branch here https://github.com/darshildpatel/in-toto-golang/tree/add-symlinks-support/in_toto . Let me know if that looks fine. I would add more test cases and an extra variable for the infinite recursion problem. 

@lukpueh I am not able to use the package fastWalk from Go tools. It seems we are not able to use word "internal" in the import statement which hinders us from using that package directly in the code. Would you have some suggestions for this ?

**Comment by lukpueh** [comment]
Thanks for looking into this, @darshildpatel! From what I read (e.g. https://github.com/golang/go/issues/4759) the go folks seem to not want to provide a public function, because it is difficult to get it right and prevent infinite loops.

This reluctancy among the experts makes me skeptical if it is a good idea to implement it by ourselves? @SantiagoTorres, what do you think?

What about trying to *verndorize* `fastwalk`? The go modules docs provide a [corresponding section](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away). @darshildpatel, would you mind reading up on it?

**Comment by darshildpatel** [comment]
Thanks @lukpueh, it seems it should work. I have implemented the fastwalk in one of my local repo. But we still have the same issue of going into infinite loops. Do you mind having a look at my recursive solution that I have on my branch currently. 
I and @SantiagoTorres were thinking of adding a count variable to the recursive approach to prevent infinite loops, but after some research I think that would have a lot of loop holes. That way we would restrict the breadth of symlink traversal along with its depth.
I was thinking of checking our artifacts dictionary before traversing the symlinks, if its already present we do not traverse it. Would you have some insights on it ?

**Comment by lukpueh** [comment]
@darshildpatel, I just reviewed your draft PR https://github.com/in-toto/in-toto-golang/pull/37#pullrequestreview-230010006. Please address my comments and ping me when you think you are done. We will look at circular symlinks afterwards, maybe even in a separate PR.
Blindly counting recursions seems a bit too easy though. IIUC others have dealt with the issue by keeping track of visited directories.

Btw. @SantiagoTorres and I agreed that vendorizing `fastwalk` adds to much overhead, so a simple custom implementation is okay, however, you can still skim through `fastwalk`'s code for inspiration.

**Comment by shibumi** [comment]
@SantiagoTorres @lukpueh I think we can close this one here :)
